create table account
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6) not null,
    created_by     bigint,
    updated_at     timestamp(6),
    updated_by     bigint,
    account_code   varchar(255)
        constraint ukah2gw5ynairyihj4glqfv5sy3
            unique,
    account_name   varchar(255) not null,
    account_number varchar(255),
    account_type   varchar(255) not null
        constraint account_account_type_check
            check ((account_type)::text = ANY
        ((ARRAY ['RECEIVABLE'::character varying, 'ADVANCE'::character varying, 'BANK'::character varying, 'CASH'::character varying, 'PAYABLE'::character varying, 'EXPENSE'::character varying, 'INCOME'::character varying])::text[]))
    );

alter table account
    owner to postgres;

create table accounting_ledger
(
    id                   bigint generated by default as identity
        primary key,
    created_at           timestamp(6)   not null,
    created_by           bigint,
    updated_at           timestamp(6),
    updated_by           bigint,
    balance              numeric(15, 2) not null,
    credit_amount        numeric(15, 2),
    currency             varchar(255)
        constraint accounting_ledger_currency_check
            check ((currency)::text = ANY
        ((ARRAY ['USD'::character varying, 'EUR'::character varying, 'GBP'::character varying, 'INR'::character varying, 'AUD'::character varying, 'BDT'::character varying])::text[])),
    debit_amount         numeric(15, 2),
    description          varchar(255),
    fiscal_period        varchar(20),
    is_active            boolean,
    is_reconciled        boolean,
    ledger_code          varchar(255),
    ledger_name          varchar(255),
    linked_document_id   varchar(255),
    linked_document_type varchar(255)
        constraint accounting_ledger_linked_document_type_check
            check ((linked_document_type)::text = ANY
                   ((ARRAY ['SALES_INVOICE'::character varying, 'PAYMENT_ENTRY'::character varying, 'DELIVERY_NOTE'::character varying])::text[])),
    posting_date         date           not null,
    reference_number     varchar(255),
    transaction_date     date           not null,
    transaction_type     varchar(255)   not null
        constraint accounting_ledger_transaction_type_check
            check ((transaction_type)::text = ANY
                   ((ARRAY ['PAYMENT'::character varying, 'INVOICE'::character varying, 'ADJUSTMENT'::character varying, 'TRANSFER'::character varying, 'ACCRUAL'::character varying])::text[])),
    account_id           bigint         not null
        constraint fkfh9wog8hqrsfpnwyimlp9nh98
            references account
);

alter table accounting_ledger
    owner to postgres;

create table contacts
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) not null,
    created_by  bigint,
    updated_at  timestamp(6),
    updated_by  bigint,
    address     varchar(255),
    department  varchar(100),
    designation varchar(100),
    email       varchar(255),
    first_name  varchar(100) not null,
    last_name   varchar(100) not null,
    phone       varchar(20),
    status      varchar(255)
        constraint contacts_status_check
            check ((status)::text = ANY
        ((ARRAY ['PASSIVE'::character varying, 'OPEN_TO_CONTACT'::character varying, 'REPLIED'::character varying])::text[]))
    );

alter table contacts
    owner to postgres;

create table contact_entity_link
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) not null,
    created_by  bigint,
    updated_at  timestamp(6),
    updated_by  bigint,
    entity_id   bigint       not null,
    entity_type varchar(255) not null
        constraint contact_entity_link_entity_type_check
            check ((entity_type)::text = ANY
        ((ARRAY ['CUSTOMER'::character varying, 'SUPPLIER'::character varying, 'LEAD'::character varying, 'SHAREHOLDER'::character varying, 'SALES_PARTNER'::character varying, 'USER'::character varying])::text[])),
    is_primary  boolean,
    contact_id  bigint       not null
        constraint fklruk39qhfx5oiaa45hi8s8hs0
            references contacts
);

alter table contact_entity_link
    owner to postgres;

create table item
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6)   not null,
    created_by       bigint,
    updated_at       timestamp(6),
    updated_by       bigint,
    item_code        varchar(50)    not null
        constraint ukmm7bf7y05rx808c7mw73iiu8q
            unique,
    item_name        varchar(255)   not null,
    price            numeric(15, 2) not null,
    quantity_on_hand numeric(15, 2) not null
);

alter table item
    owner to postgres;

create table payment_terms
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) not null,
    created_by  bigint,
    updated_at  timestamp(6),
    updated_by  bigint,
    description varchar(255),
    net_days    integer,
    terms_name  varchar(255) not null
);

alter table payment_terms
    owner to postgres;

create table price_list
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp(6)     not null,
    created_by        bigint,
    updated_at        timestamp(6),
    updated_by        bigint,
    currency_code     varchar(3)       not null,
    description       varchar(255),
    markup_percentage double precision not null,
    price_list_name   varchar(255)     not null
);

alter table price_list
    owner to postgres;

create table customer_group
(
    id                    bigint generated by default as identity
        primary key,
    created_at            timestamp(6) not null,
    created_by            bigint,
    updated_at            timestamp(6),
    updated_by            bigint,
    credit_limit          numeric(19, 2),
    customer_group_name   varchar(255) not null,
    group_node            boolean      not null,
    advance_account_id    bigint
        constraint fkb4kyjp70n6t0gtt89kqya5b6a
            references account,
    parent_group_id       bigint
        constraint fkqjsaq55dhld1xq2ws0tf34igb
            references customer_group,
    payment_terms_id      bigint
        constraint fkoy2eldvfyqjyypts6jjqloykh
            references payment_terms,
    price_list_id         bigint
        constraint fk8s2k6mrko7c9ejj19f6ld47gd
            references price_list,
    receivable_account_id bigint
        constraint fkby15uy3ulwu0ybe2dfn40w53c
            references account
);

alter table customer_group
    owner to postgres;

create table salesperson
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6) not null,
    created_by   bigint,
    updated_at   timestamp(6),
    updated_by   bigint,
    email        varchar(255),
    first_name   varchar(255),
    last_name    varchar(255),
    phone_number varchar(255)
);

alter table salesperson
    owner to postgres;

create table sales_target
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6) not null,
    created_by     bigint,
    updated_at     timestamp(6),
    updated_by     bigint,
    end_date       date,
    start_date     date,
    target_amount  numeric(19, 2),
    salesperson_id bigint
        constraint fkl3wqwrc0527ygl9a0ryk2kric
            references salesperson
);

alter table sales_target
    owner to postgres;

create table territory
(
    id                   bigint generated by default as identity
        primary key,
    created_at           timestamp(6) not null,
    created_by           bigint,
    updated_at           timestamp(6),
    updated_by           bigint,
    region               varchar(255),
    territory_name       varchar(255),
    territory_status     varchar(255) not null
        constraint territory_territory_status_check
            check ((territory_status)::text = ANY
        ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])),
    territory_manager_id bigint
        constraint fk2kekihfxu30sxsoq0vlvl3a37
            references salesperson
);

alter table territory
    owner to postgres;

create table campaign
(
    id                   bigint generated by default as identity
        primary key,
    created_at           timestamp(6) not null,
    created_by           bigint,
    updated_at           timestamp(6),
    updated_by           bigint,
    campaign_description text,
    campaign_name        varchar(255) not null,
    campaign_type        varchar(255) not null
        constraint campaign_campaign_type_check
            check ((campaign_type)::text = ANY
        ((ARRAY ['EMAIL'::character varying, 'SOCIAL_MEDIA'::character varying, 'TELEMARKETING'::character varying, 'DIRECT_MAIL'::character varying, 'EVENT'::character varying, 'WEBINAR'::character varying, 'CONTENT_MARKETING'::character varying, 'PPC_ADVERTISING'::character varying, 'SEO_CAMPAIGN'::character varying, 'INFLUENCER_MARKETING'::character varying])::text[])),
    end_date             date         not null,
    start_date           date         not null,
    status               varchar(255) not null
        constraint campaign_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PLANNED'::character varying, 'ACTIVE'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'ON_HOLD'::character varying])::text[])),
    territory_id         bigint
        constraint fk4q82lg6j1q8g4wap969pvlg8d
            references territory
);

alter table campaign
    owner to postgres;

create table customer
(
    id                   bigint generated by default as identity
        primary key,
    created_at           timestamp(6) not null,
    created_by           bigint,
    updated_at           timestamp(6),
    updated_by           bigint,
    billing_currency     varchar(3),
    credit_limit         numeric(19, 2),
    customer_name        varchar(255) not null,
    customer_type        varchar(255) not null
        constraint customer_customer_type_check
            check ((customer_type)::text = ANY
        ((ARRAY ['INDIVIDUAL'::character varying, 'CORPORATE'::character varying, 'GOVERNMENT'::character varying, 'NON_PROFIT'::character varying, 'OTHER'::character varying])::text[])),
    accounting_ledger_id bigint
        constraint fkogna5eleao6a4pjiorl3txcjj
            references accounting_ledger,
    customer_group       bigint
        constraint fksj8kugj8w0x16teei93oq837t
            references customer_group,
    payment_terms_id     bigint
        constraint fkbkp08qc62rmjotnj07djr5xp2
            references payment_terms,
    price_list_id        bigint
        constraint fkdy9yo0g543vri6m5ev1aj2d5
            references price_list,
    territory_id         bigint
        constraint fkaamb70smwnslvwf80j4bc50c4
            references territory
);

alter table customer
    owner to postgres;

create table customer_sales_person
(
    customer_id     bigint not null
        constraint fk3cd7ob83rg2u9cg52h7id3072
            references customer,
    sales_person_id bigint not null
        constraint fkt5swl7y3t643lhwft0gdd4lxk
            references salesperson,
    primary key (customer_id, sales_person_id)
);

alter table customer_sales_person
    owner to postgres;

create table lead
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6) not null,
    created_by    bigint,
    updated_at    timestamp(6),
    updated_by    bigint,
    email         varchar(255),
    phone         varchar(255),
    lead_name     varchar(255),
    lead_rating   integer,
    lead_source   varchar(255)
        constraint lead_lead_source_check
            check ((lead_source)::text = ANY
        ((ARRAY ['WEBSITE'::character varying, 'REFERRAL'::character varying, 'SOCIAL_MEDIA'::character varying, 'EMAIL_CAMPAIGN'::character varying, 'TRADE_SHOW'::character varying, 'COLD_CALL'::character varying, 'ADVERTISEMENT'::character varying])::text[])),
    lead_status   varchar(255)
        constraint lead_lead_status_check
            check ((lead_status)::text = ANY
                   ((ARRAY ['OPEN'::character varying, 'CLOSED'::character varying, 'LOST'::character varying, 'QUALIFIED'::character varying, 'UNQUALIFIED'::character varying, 'CONVERTED'::character varying, 'REJECTED'::character varying])::text[])),
    lead_owner_id bigint
        constraint fkkmdu4fqj9wo30rw4yvul11i47
            references salesperson,
    territory_id  bigint
        constraint fkdnq0i5ujlfsi3mtwf7eel9rtw
            references territory
);

alter table lead
    owner to postgres;

create table opportunity
(
    id                     bigint generated by default as identity
        primary key,
    created_at             timestamp(6) not null,
    created_by             bigint,
    updated_at             timestamp(6),
    updated_by             bigint,
    currency               varchar(3)   not null
        constraint opportunity_currency_check
            check ((currency)::text = ANY
        ((ARRAY ['USD'::character varying, 'EUR'::character varying, 'GBP'::character varying, 'INR'::character varying, 'AUD'::character varying, 'BDT'::character varying])::text[])),
    estimated_value        numeric(15, 2),
    next_contact_date      date,
    opportunity_from       varchar(10)  not null
        constraint opportunity_opportunity_from_check
            check ((opportunity_from)::text = ANY
                   ((ARRAY ['LEAD'::character varying, 'CUSTOMER'::character varying])::text[])),
    opportunity_name       varchar(255) not null,
    opportunity_stage      varchar(15)  not null
        constraint opportunity_opportunity_stage_check
            check ((opportunity_stage)::text = ANY
                   ((ARRAY ['PROSPECTING'::character varying, 'QUALIFICATION'::character varying, 'NEEDS_ANALYSIS'::character varying, 'VALUE_PROPOSITION'::character varying, 'PROPOSAL'::character varying, 'NEGOTIATION'::character varying, 'CLOSED_WON'::character varying, 'CLOSED_LOST'::character varying])::text[])),
    opportunity_type       varchar(20)  not null
        constraint opportunity_opportunity_type_check
            check ((opportunity_type)::text = ANY
                   ((ARRAY ['SALES'::character varying, 'SUPPORT'::character varying, 'MAINTENANCE'::character varying])::text[])),
    probability_of_closing integer,
    source                 varchar(100),
    customer_id            bigint
        constraint fkov0mdcjiekto2qxferfbk6nt0
            references customer,
    lead_id                bigint
        constraint fkjne12qk02v3txj39pdxg2lm4t
            references lead,
    next_contact_by        bigint
        constraint fke9i6c85xp56e7xqu67yoi8hd0
            references salesperson,
    opportunity_owner      bigint       not null
        constraint fk2wd7j5xeptjinpeg4ydfhl9wn
            references salesperson,
    sales_campaign         bigint
        constraint fk5pxuex4tp1dbo27icn1qts6cx
            references campaign
);

alter table opportunity
    owner to postgres;

create table opportunity_item
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6) not null,
    created_by     bigint,
    updated_at     timestamp(6),
    updated_by     bigint,
    quantity       integer      not null,
    item_id        bigint       not null
        constraint fk8vg51yl71w5yr57j96f094abt
            references item,
    opportunity_id bigint       not null
        constraint fkf41cjte458eehix1758545kb4
            references opportunity
);

alter table opportunity_item
    owner to postgres;

create table sales_order
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) not null,
    created_by       bigint,
    updated_at       timestamp(6),
    updated_by       bigint,
    delivery_date    timestamp(6),
    order_date       timestamp(6),
    order_number     varchar(255),
    status           varchar(255)
        constraint sales_order_status_check
            check ((status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'CONFIRMED'::character varying, 'SHIPPED'::character varying, 'COMPLETED'::character varying])::text[])),
    total_amount     numeric(38, 2),
    customer_id      bigint       not null
        constraint fkqqe3xj99rblvm5n0h0cp48gsa
            references customer,
    payment_terms_id bigint
        constraint fkegw06e8xg2oueob9x8rycvubg
            references payment_terms
);

alter table sales_order
    owner to postgres;

create table delivery_note
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) not null,
    created_by       bigint,
    updated_at       timestamp(6),
    updated_by       bigint,
    delivery_date    date         not null,
    status           varchar(255)
        constraint delivery_note_status_check
            check ((status)::text = ANY
        ((ARRAY ['PREPARED'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying])::text[])),
    delivery_note_id bigint       not null
        constraint fkcydnugaxufw0u5l72w6c31rwp
            references sales_order
);

alter table delivery_note
    owner to postgres;

create table delivery_note_items
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) not null,
    created_by       bigint,
    updated_at       timestamp(6),
    updated_by       bigint,
    item_code        varchar(255),
    quantity         integer,
    delivery_note_id bigint       not null
        constraint fkcjt58tv06077ki26i23wel384
            references delivery_note
);

alter table delivery_note_items
    owner to postgres;

create table sales_invoice
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) not null,
    created_by       bigint,
    updated_at       timestamp(6),
    updated_by       bigint,
    customer_address varchar(255),
    customer_name    varchar(255),
    discount_amount  double precision,
    invoice_date     timestamp(6),
    invoice_number   varchar(255),
    net_amount       double precision,
    payment_status   varchar(255)
        constraint sales_invoice_payment_status_check
            check ((payment_status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying, 'PARTIALLY_REFUNDED'::character varying, 'CANCELLED'::character varying])::text[])),
    status           varchar(255)
        constraint sales_invoice_status_check
            check ((status)::text = ANY
                   ((ARRAY ['DRAFT'::character varying, 'SENT'::character varying, 'PAID'::character varying])::text[])),
    tax_amount       double precision,
    total_amount     double precision,
    sales_order_id   bigint       not null
        constraint fksopndnwecrebe8wh6dngljp4m
            references sales_order
);

alter table sales_invoice
    owner to postgres;

create table payment_entry
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6) not null,
    created_by     bigint,
    updated_at     timestamp(6),
    updated_by     bigint,
    amount         numeric(38, 2),
    payment_date   timestamp(6),
    payment_method varchar(255)
        constraint payment_entry_payment_method_check
            check ((payment_method)::text = ANY
        ((ARRAY ['CASH'::character varying, 'CHECK'::character varying, 'DEBIT_CARD'::character varying, 'CREDIT_CARD'::character varying])::text[])),
    status         varchar(255)
        constraint payment_entry_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying, 'PARTIALLY_REFUNDED'::character varying, 'CANCELLED'::character varying])::text[])),
    invoice_id     bigint       not null
        constraint fksrijeyhcudhj7lidkj6yl5plr
            references sales_invoice
);

alter table payment_entry
    owner to postgres;

create table sales_order_item
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6) not null,
    created_by     bigint,
    updated_at     timestamp(6),
    updated_by     bigint,
    item_code      varchar(255),
    price          numeric(38, 2),
    quantity       integer,
    sales_order_id bigint       not null
        constraint fkfkfkjlvt4m5xfft7bys91twfn
            references sales_order
);

alter table sales_order_item
    owner to postgres;

